apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: container-registry
  name: docker-registry-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: docker-registry-local-storage